name: Preview Deploy on PR w/ App Changes

on:
  pull_request:
    paths:
    - "src/**"
    - "public/**"
jobs:
  build_and_preview:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Firebase Preview URL
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          expires: 7d
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CLOUDPONICS_BC383 }}'
          projectId: cloudponics-bc383